template:
    - sensor:
          - name: 'Family Board Home Controls Unavailable'
            unique_id: family_board_home_controls_unavailable
            state: >
                {% set controls = [
                  'light.bedroom','light.toby','light.lizzie','light.hallway_up','light.hallway_down',
                  'switch.heater_up','switch.heater_down'
                ] %}
                {% set ns = namespace(count=0) %}
                {% for e in controls %}
                  {% if states(e) in ['unknown','unavailable','none'] %}
                    {% set ns.count = ns.count + 1 %}
                  {% endif %}
                {% endfor %}
                {{ ns.count }}
